product-service-uri: ${PRODUCT_SERVICE_URI:http://localhost:8080}

server:
  port: 8081

spring:
  application:
    name: order-service
    cloud:
      stream:
        bindings:
          order-channel:
            destination: order-channel
        rabbit:
          binder:
            connection-name-prefix: ${spring.application.name}
          bindings:
            order-channel:
              producer:
                auto-bind-dlq: true
                prefix: nab.
                dead-letter-exchange: nab.order-channel.dlx
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:icommerce}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:changeit}
  sql:
    init:
      schema-locations: classpath*:db/migration/schema-h2.sql
      platform: h2
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
  h2:
    console:
      enabled: true
